cmake_minimum_required(VERSION 3.20)
project(example_application LANGUAGES CXX)
find_package(Threads REQUIRED)
add_executable(application main.cpp)
target_compile_features(application PRIVATE cxx_std_20)
target_link_libraries(application PRIVATE Threads::Threads)
install(TARGETS application RUNTIME DESTINATION bin)
